#!/usr/bin/env node
// Build chunk-c.json (P00-T02c) chapters 59..87
import { writeFile, mkdir, unlink } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const sha=s=>'sha256:'+createHash('sha256').update(s,'utf8').digest('hex');
const R=[],X=[];let i=0;
const id=()=>'REQ-TEMP-C-'+String(++i).padStart(4,'0');
// [ch,loc,norm,cat,owners,planned,testId,excerpt,statement,num?,title?]
// num format: unit|min:N|max:N|value:N|lo..hi; multiple separated by ;
const M=r=>{
  const [ch,loc,norm,cat,own,pln,tid,exc,stmt,num,title]=r;
  const owners=own.split(',').map(s=>s.trim()).filter(Boolean);
  const tids=tid.split(',').map(s=>s.trim()).filter(Boolean);
  let vt='static';
  if(cat==='Sim'||cat==='Save'||cat==='Perf'||cat==='Security')vt='unit';
  else if(cat==='UX'||cat==='A11y')vt='visual';
  else if(cat==='QA')vt='integration';
  else if(cat==='Android'||cat==='iOS')vt='native';
  else if(cat==='Store')vt='review';
  else if(cat==='Product')vt='review';
  const nc=[];
  if(num)for(const p of num.split(';').map(s=>s.trim()).filter(Boolean)){
    const[u,e]=p.split('|').map(s=>s.trim());const o={unit:u};
    if(e.includes('..')){const[lo,hi]=e.split('..').map(Number);o.min=lo;o.max=hi;}
    else if(e.startsWith('min:'))o.min=Number(e.slice(4));
    else if(e.startsWith('max:'))o.max=Number(e.slice(4));
    else o.value=Number(e);
    nc.push(o);
  }
  R.push({id:id(),title:title??stmt.slice(0,60),statement:stmt,norm,category:cat,source:{sourceId:'gdd-v5',chapter:ch,section:null,locator:loc,quoteHash:sha(exc),originalExcerpt:exc},ownerPhases:owners,verification:[{type:vt,plannedPhase:pln,testIds:tids}],numericConstraints:nc,relatedNormIds:[],relatedScreenIds:[],status:'planned',notes:null});
};

// === CH 59 ===
M([59,'block:1779','MUST','Content','PHASE-01','PHASE-01','UT-SCHEMA-CONTENT-001','Alle Gameplayinhalte liegen als UTF-8 JSON ohne Kommentare unter src/game/content/data. Eine Datei pro Entitätskategorie, große Pools nach Region geteilt.','Alle Gameplayinhalte liegen als UTF-8 JSON ohne Kommentare unter src/game/content/data; eine Datei pro Entitätskategorie, große Pools nach Region geteilt.','','UTF-8 JSON Content-Layout']);
M([59,'block:1780','MUST','Content','PHASE-01','PHASE-01','UT-SCHEMA-ZOD-001','Zod-Schemas sind SSOT. Aus ihnen werden TypeScript-Typen, JSON Schemas und Dokumentationsreports generiert.','Zod-Schemas sind die Single Source of Truth; aus ihnen werden TypeScript-Typen, JSON Schemas und Dokumentationsreports generiert.','','Zod-Schemas als SSOT']);
M([59,'block:1781','MUST_NOT','Content','PHASE-01','PHASE-01','UT-CONTENT-LOOKUP-001','Der Build erzeugt immutable ContentIndex-Maps nach ID. Runtime-Suche über frei formulierte Namen ist verboten.','Der Build erzeugt immutable ContentIndex-Maps nach ID; Runtime-Suche über frei formulierte Namen ist verboten.','','Verbot Runtime-Namen-Suche']);
M([59,'block:1782','SHOULD','Content','PHASE-02','PHASE-02','UT-LOADER-TICKS-001','Alle Sekundenwerte in Autorendaten dürfen Dezimalzahlen sein; Loader wandelt sie einmal in ganze Ticks und protokolliert Rundung > 0,01 s als Warnung.','Sekundenwerte in Autorendaten werden einmal in ganze Ticks konvertiert; Rundung > 0,01 s wird als Warnung protokolliert.','s|min:0.01','Sekundenwerte in Ticks']);
M([59,'block:1783','MUST','Content','PHASE-01','PHASE-01','UT-LOCALE-KEYS-001','Localization Keys müssen in de und en existieren. Pseudo-Localization muss jedes Layout ohne unersetzte Schlüssel rendern.','Localization Keys müssen in de und en existieren; Pseudo-Localization muss jedes Layout ohne unersetzte Schlüssel rendern.','','Lokalisierungs-Keys DE/EN']);
M([59,'block:1785','MUST','QA','PHASE-01','PHASE-01','UT-VALID-REF-001','Referenzen: Unbekannter Held, Effekt, Fähigkeit, Lootpool, Mission oder Localization Key.','Build-Validator „Referenzen": harter Fehler bei unbekanntem Held, Effekt, Fähigkeit, Lootpool, Mission oder Localization Key.','','Build-Validator Referenzen']);
M([59,'block:1785','MUST','QA','PHASE-01','PHASE-01','UT-VALID-IDS-001','IDs: Duplikat, Großbuchstabe, Leerzeichen, nachträglich entfernte veröffentlichte ID ohne Migration.','Build-Validator „IDs": harter Fehler bei Duplikat, Großbuchstabe, Leerzeichen, nachträglich entfernter veröffentlichter ID ohne Migration.','','Build-Validator IDs']);
M([59,'block:1785','MUST','QA','PHASE-02','PHASE-02','UT-VALID-COMBAT-001','Kampf: Negative LP, Cooldown < 0,45 s ohne Ausnahme, ungültige Phase, unendliche Triggerkette.','Build-Validator „Kampf": harter Fehler bei negativer LP, Cooldown < 0,45 s ohne Ausnahme, ungültiger Phase, unendlicher Triggerkette.','s|max:0.45','Build-Validator Kampf']);
M([59,'block:1785','MUST','QA','PHASE-02','PHASE-02','UT-VALID-FORMATION-001','Formation: Mehr als Plätze/Kopien/Helden, identische Startfelder, nicht erreichbare Pflichtbahn.','Build-Validator „Formation": harter Fehler bei Überschreitung Plätze/Kopien/Helden, identischen Startfeldern, nicht erreichbarer Pflichtbahn.','','Build-Validator Formation']);
M([59,'block:1785','MUST','QA','PHASE-02','PHASE-02','UT-VALID-SUMMON-001','Beschwörung: Mehr als sechs ohne Ersatzregel, Rekursion ohne Safety Cap.','Build-Validator „Beschwörung": harter Fehler bei mehr als sechs ohne Ersatzregel oder Rekursion ohne Safety Cap.','count|max:6','Build-Validator Beschwörung']);
M([59,'block:1785','MUST','QA','PHASE-04','PHASE-04','UT-VALID-DUNGEON-001','Dungeon: Nicht erreichbarer Boss, kein Anker, keine Vorbereitung, >13 sichtbare oder >8 besuchte Knoten ohne Modusausnahme.','Build-Validator „Dungeon": harter Fehler bei nicht erreichbarem Boss, fehlendem Anker, fehlender Vorbereitung, >13 sichtbaren oder >8 besuchten Knoten ohne Modusausnahme.','count|max:13','Build-Validator Dungeon']);
M([59,'block:1785','MUST','QA','PHASE-04','PHASE-04','UT-VALID-LOOT-001','Loot: Leerer Pool, Erstbelohnung ohne Ersatz, nicht besitzbares Item.','Build-Validator „Loot": harter Fehler bei leerem Pool, Erstbelohnung ohne Ersatz, nicht besitzbarem Item.','','Build-Validator Loot']);
M([59,'block:1785','MUST','Content','PHASE-01','PHASE-01','UT-VALID-TEXT-001','Text: Fehlende Sprache, Kurztooltip >220 Zeichen, Buttonlabel >30 Zeichen ohne approved compact variant.','Build-Validator „Text": harter Fehler bei fehlender Sprache, Kurztooltip >220 Zeichen, Buttonlabel >30 Zeichen ohne approved compact variant.','chars|max:220','Build-Validator Text']);
M([59,'block:1785','MUST','Content','PHASE-10','PHASE-10','UT-VALID-ASSETS-001','Assets: Fehlendes Manifest, Atlas >2048, unbekannter Audio Cue, nicht lizenziertes Asset.','Build-Validator „Assets": harter Fehler bei fehlendem Manifest, Atlas >2048, unbekanntem Audio Cue, nicht lizenziertem Asset.','px|max:2048','Build-Validator Assets']);
M([59,'block:1785','MUST_NOT','Store','PHASE-10','PHASE-10','UT-VALID-STORE-001','Store: Produktionsbuild enthält server.url, INTERNET-Permission, Debuggable, Remote Script oder verbotenen SDK-Identifier.','Build-Validator „Store": harter Fehler, wenn Produktionsbuild server.url, INTERNET-Permission, Debuggable, Remote Script oder verbotenen SDK-Identifier enthält.','','Build-Validator Store']);

// === CH 60 ===
M([60,'block:1790','MUST','Content','PHASE-01','PHASE-01','UT-LOCALE-PARITY-001','Release-Sprachen sind Deutsch und Englisch. Deutsch ist narrative Autorensprache; Englisch ist vollständig geprüfte Parität, keine maschinelle Rohübersetzung im Release.','Release-Sprachen sind Deutsch und Englisch; Deutsch ist narrative Autorensprache, Englisch ist vollständig geprüfte Parität ohne maschinelle Rohübersetzung im Release.','','Release-Sprachen DE/EN']);
M([60,'block:1791','MUST','Content','PHASE-01','PHASE-01','UT-LOCALE-ICU-001','Alle sichtbaren Strings liegen außerhalb des Codes. ICU MessageFormat wird für Plural, Zahl und grammatische Varianten verwendet.','Alle sichtbaren Strings liegen außerhalb des Codes; ICU MessageFormat wird für Plural, Zahl und grammatische Varianten verwendet.','','Strings außerhalb Code/ICU']);
M([60,'block:1792','SHOULD','Content','PHASE-01','PHASE-01','UT-LOCALE-DIRECTION-001','Richtungsbegriffe links/rechts werden in Gameplaytexten vermieden; Spieler/Gegner, oben/Mitte/unten bleiben eindeutig bei Spiegelung.','Richtungsbegriffe links/rechts werden in Gameplaytexten vermieden; Spieler/Gegner, oben/Mitte/unten bleiben eindeutig bei Spiegelung.','','Richtungsangaben vermeiden']);
M([60,'block:1793','MUST','UX','PHASE-09','PHASE-09','UT-LOCALE-COMPACT-001','UI-Labels besitzen eine kurze und optional compact Variante. Kein Agent darf Text durch kleinere Schrift passend machen, solange eine Reflow-/Compact-Lösung möglich ist.','UI-Labels besitzen eine kurze und optional compact Variante; Text darf nicht durch kleinere Schrift passend gemacht werden, solange eine Reflow-/Compact-Lösung möglich ist.','','UI-Labels mit Compact']);
M([60,'block:1794','MUST','Content','PHASE-01','PHASE-01','UT-LOCALE-MISSING-001','Fehlende Übersetzung zeigt im Development den Key in Magenta und ist im Release ein Buildfehler.','Fehlende Übersetzung zeigt im Development den Key in Magenta und ist im Release ein Buildfehler.','','Fehlende Übersetzung Buildfehler']);
M([60,'block:1795','MUST','Content','PHASE-09','PHASE-09','UT-LOCALE-PSEUDO-001','Pseudo-Locale erweitert Texte um 35%, setzt Akzente und markiert Start/Ende. Alle Screens werden damit im visuellen Test gerendert.','Pseudo-Locale erweitert Texte um 35%, setzt Akzente und markiert Start/Ende; alle Screens werden damit im visuellen Test gerendert.','pct|min:35','Pseudo-Locale']);
M([60,'block:1796','MUST','UX','PHASE-09','PHASE-09','UT-LOCALE-BTNDE-001','Primärbutton: 30 Zeichen DE; 24 EN oder Compact Key.','Texttyp „Primärbutton": maximal 30 Zeichen DE.','chars|max:30','Textlänge Primärbutton DE']);
M([60,'block:1796','MUST','UX','PHASE-09','PHASE-09','UT-LOCALE-BTNEN-001','Primärbutton: 30 Zeichen DE; 24 EN oder Compact Key.','Texttyp „Primärbutton" EN: maximal 24 Zeichen oder Compact Key.','chars|max:24','Textlänge Primärbutton EN']);
M([60,'block:1796','MUST','UX','PHASE-09','PHASE-09','UT-LOCALE-TOOLTIP-001','Kurztooltip: 220 Zeichen inklusive Leerzeichen.','Texttyp „Kurztooltip": maximal 220 Zeichen inklusive Leerzeichen.','chars|max:220','Textlänge Kurztooltip']);
M([60,'block:1796','MUST','Content','PHASE-01','PHASE-01','UT-LOCALE-CARD-001','Kartentext: Titel 34; Unterzeile 60; Effekt 180 Zeichen.','Texttyp „Kartentext": Titel 34; Unterzeile 60; Effekt 180 Zeichen.','chars|max:180','Textlänge Kartentext']);
M([60,'block:1796','MUST','Content','PHASE-04','PHASE-04','UT-LOCALE-EVTINTRO-001','Ereignisintro: 480 Zeichen, max. zwei Absätze.','Texttyp „Ereignisintro": 480 Zeichen, maximal zwei Absätze.','chars|max:480','Textlänge Ereignisintro']);
M([60,'block:1796','MUST','Content','PHASE-04','PHASE-04','UT-LOCALE-EVTOPT-001','Ereignisoption: Titel 46; Folge 180 Zeichen.','Texttyp „Ereignisoption": Titel 46; Folge 180 Zeichen.','chars|max:180','Textlänge Ereignisoption']);
M([60,'block:1796','MUST','UX','PHASE-09','PHASE-09','UT-LOCALE-PIP-001','Pip-Hinweis: Zwei Sätze, zusammen <= 180 Zeichen.','Texttyp „Pip-Hinweis": Zwei Sätze, zusammen <= 180 Zeichen.','chars|max:180','Textlänge Pip-Hinweis']);
M([60,'block:1796','MUST','UX','PHASE-04','PHASE-04','UT-LOCALE-BOSSPREVIEW-001','Bossvorschau: Vier Kernbullets je <= 120 Zeichen plus Details.','Texttyp „Bossvorschau": Vier Kernbullets je <= 120 Zeichen plus Details.','chars|max:120','Textlänge Bossvorschau']);
M([60,'block:1796','MUST','Content','PHASE-09','PHASE-09','UT-LOCALE-SUBTITLE-001','Untertitel: Max. 42 Zeichen pro Zeile, zwei Zeilen; Lesedauer min. 1,2 s.','Texttyp „Untertitel": Max. 42 Zeichen pro Zeile, zwei Zeilen; Lesedauer min. 1,2 s.','s|min:1.2;chars|max:42','Textlänge Untertitel']);

// === CH 61 ===
M([61,'block:1800','MUST_NOT','Security','PHASE-10','PHASE-10','UT-SEC-PRIVACY-001','Die Release-App sammelt, überträgt oder teilt keine Nutzer-, Geräte-, Werbe-, Standort-, Nutzungs- oder Diagnosedaten. Es existiert kein Backend.','Die Release-App sammelt, überträgt oder teilt keine Nutzer-, Geräte-, Werbe-, Standort-, Nutzungs- oder Diagnosedaten; es existiert kein Backend.','','Keine Datenerhebung']);
M([61,'block:1801','MUST','Security','PHASE-12','PHASE-12','UT-SEC-LOGS-001','Alle Statistiken, Replays und Logs bleiben lokal. Diagnoseexport erfolgt nur nach expliziter Nutzeraktion und zeigt vor dem Systemdialog den enthaltenen Umfang.','Alle Statistiken, Replays und Logs bleiben lokal; Diagnoseexport erfolgt nur nach expliziter Nutzeraktion und zeigt vor dem Systemdialog den enthaltenen Umfang.','','Lokale Logs/Diagnose']);
M([61,'block:1802','MUST_NOT','Security','PHASE-10','PHASE-10','UT-SEC-IDS-001','Keine Advertising ID, IDFV, Android ID, Install Referrer, IP-Logging, Fingerprinting oder Geräteidentifier werden gelesen.','Es werden keine Advertising ID, IDFV, Android ID, Install Referrer, IP-Logging, Fingerprinting oder Geräteidentifier gelesen.','','Verbot Identifier']);
M([61,'block:1803','MUST','Security','PHASE-10','PHASE-10','UT-SEC-PRIVACYDECL-001','Die Datenschutzseite und die Store-Deklarationen müssen „keine Datenerhebung/-weitergabe" widerspruchsfrei abbilden. Drittbibliotheken werden vor Release auf Netzwerk- und Identifierzugriff geprüft.','Datenschutzseite und Store-Deklarationen bilden „keine Datenerhebung/-weitergabe" widerspruchsfrei ab; Drittbibliotheken werden vor Release auf Netzwerk- und Identifierzugriff geprüft.','','Datenschutzdeklaration konsistent']);
M([61,'block:1804','MUST','UX','PHASE-10','PHASE-10','UT-SEC-LINKS-001','Externe Datenschutz-, Support- und Lizenzlinks öffnen im Systembrowser. Die App lädt deren Inhalte nicht in einen kontrollierten WebView.','Externe Datenschutz-, Support- und Lizenzlinks öffnen im Systembrowser; die App lädt deren Inhalte nicht in einen kontrollierten WebView.','','Externe Links Systembrowser']);
M([61,'block:1806','MUST','Security','PHASE-10','PHASE-10','UT-SEC-CSP-001',"default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; font-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'none'; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'",'Produktions-CSP: default-src self; img-src self data: blob:; media-src self blob:; font-src self; style-src self unsafe-inline; script-src self; connect-src none; object-src none; frame-src none; base-uri none; form-action none.','','Produktions-CSP']);
M([61,'block:1807','MUST','Security','PHASE-10','PHASE-10','UT-SEC-CONNECT-001','connect-src none ist im Produktionsbuild Pflicht. Jeder unbeabsichtigte fetch/WebSocket/EventSource schlägt sichtbar im Test fehl.','connect-src none ist im Produktionsbuild Pflicht; jeder unbeabsichtigte fetch/WebSocket/EventSource schlägt sichtbar im Test fehl.','','connect-src none Pflicht']);
M([61,'block:1808','MUST_NOT','Security','PHASE-10','PHASE-10','UT-SEC-CAPCONFIG-001','capacitor.config enthält im Release keine server.url, cleartext, allowNavigation oder mixed content. WebView-Debugging ist deaktiviert.','capacitor.config enthält im Release keine server.url, cleartext, allowNavigation oder mixed content; WebView-Debugging ist deaktiviert.','','capacitor.config produktionsfest']);
M([61,'block:1809','MUST_NOT','Android','PHASE-10','PHASE-10','UT-AND-INTERNET-001','Android INTERNET-Permission wird im finalen Manifest entfernt. VIBRATE ist die einzige optionale normale Permission; keine Runtime-Permissions.','Android INTERNET-Permission wird im finalen Manifest entfernt; VIBRATE ist die einzige optionale normale Permission; keine Runtime-Permissions.','','Android INTERNET entfernt']);
M([61,'block:1810','MUST_NOT','iOS','PHASE-10','PHASE-10','UT-IOS-ENTITLE-001','iOS besitzt keine unnötigen Entitlements. PrivacyInfo.xcprivacy nennt nur tatsächlich genutzte Required-Reason APIs aus Capacitor/Plugins.','iOS besitzt keine unnötigen Entitlements; PrivacyInfo.xcprivacy nennt nur tatsächlich genutzte Required-Reason APIs aus Capacitor/Plugins.','','iOS Privacy Manifest minimal']);
M([61,'block:1811','MUST_NOT','Security','PHASE-10','PHASE-10','UT-SEC-EVAL-001','Keine eval/new Function/dynamische Scriptinjektion. Sourcemaps werden intern archiviert, nicht öffentlich mitgeliefert.','Keine eval/new Function/dynamische Scriptinjektion; Sourcemaps werden intern archiviert, nicht öffentlich mitgeliefert.','','Verbot eval/Remote Script']);
M([61,'block:1813','MUST','Security','PHASE-01','PHASE-01','UT-SEC-DEPS-001','Nur direkte Dependencies mit klarer Funktion. Neue Dependency benötigt Lizenz-, Größe-, Netzwerk-, Permission- und Maintenance-Prüfung.','Nur direkte Dependencies mit klarer Funktion; neue Dependency benötigt Lizenz-, Größe-, Netzwerk-, Permission- und Maintenance-Prüfung.','','Dependency-Aufnahmeprüfung']);
M([61,'block:1814','MUST','Security','PHASE-20','PHASE-20','UT-SEC-AUDIT-001','CI führt pnpm audit oder gleichwertigen Advisory-Scan aus. Kritische/hohe ausnutzbare Findings blockieren Release.','CI führt pnpm audit oder gleichwertigen Advisory-Scan aus; kritische/hohe ausnutzbare Findings blockieren Release.','','CI Dependency-Audit']);
M([61,'block:1815','MUST','Security','PHASE-20','PHASE-20','UT-SEC-PROVENANCE-001','Alle Store-Artefakte werden aus clean checkout mit frozen lockfile gebaut. Buildprovenienz, Commit und Dependencyliste werden archiviert.','Alle Store-Artefakte werden aus clean checkout mit frozen lockfile gebaut; Buildprovenienz, Commit und Dependencyliste werden archiviert.','','Buildprovenienz archiviert']);
M([61,'block:1816','MUST','Content','PHASE-15','PHASE-15','UT-SEC-ASSETLIC-001','Drittanbieterassets benötigen Lizenzdatei, Quelle, Autor und kommerzielle Nutzungsfreigabe im Assetmanifest.','Drittanbieterassets benötigen Lizenzdatei, Quelle, Autor und kommerzielle Nutzungsfreigabe im Assetmanifest.','','Asset-Lizenznachweis']);

// === CH 62 ===
M([62,'block:1819','MUST','Android','PHASE-05','PHASE-05','UT-AND-MINSDK-001','minSdk | 24 (Android 7.0), entsprechend Capacitor-8-Minimum.','minSdk ist 24 (Android 7.0), entsprechend Capacitor-8-Minimum.','api|min:24','Android minSdk 24']);
M([62,'block:1819','MUST','Android','PHASE-05','PHASE-05','UT-AND-COMPILE-001','compile/target | 36; vor Storeupload auf aktuell von Play verlangte oder höhere stabile API prüfen.','compile/target ist 36; vor Storeupload wird auf aktuell von Play verlangte oder höhere stabile API geprüft.','api|min:36','Android compile/target API']);
M([62,'block:1819','MUST','Android','PHASE-10','PHASE-10','UT-AND-AAB-001','Packaging | Android App Bundle .aab; Play App Signing aktiv; kein APK als Produktionsupload.','Android App Bundle .aab; Play App Signing aktiv; kein APK als Produktionsupload.','','AAB Verpackung']);
M([62,'block:1819','MUST','Android','PHASE-10','PHASE-10','UT-AND-ABI-001','ABI | Release-AAB enthält arm64-v8a und armeabi-v7a, sofern Native-Code ABI-Slices erzeugt; beide müssen 16-KB-seitensicher sein. x86_64 ist ausschließlich für Emulator-/QA-Builds und wird nicht als Production-Slice ausgeliefert.','Release-AAB enthält arm64-v8a und armeabi-v7a, sofern Native-Code ABI-Slices erzeugt; beide müssen 16-KB-seitensicher sein; x86_64 ist ausschließlich für Emulator-/QA-Builds und wird nicht als Production-Slice ausgeliefert.','','Release-ABI-Slices']);
M([62,'block:1819','MUST','Android','PHASE-10','PHASE-10','UT-AND-16KB-001','16-KB-Seiten | Alle Native-Libs kompatibel; bundletool/APK Analyzer und 16-KB-Testgerät/Emulator als Gate.','Alle Native-Libs sind 16-KB-kompatibel; bundletool/APK Analyzer und 16-KB-Testgerät/Emulator sind Gate.','','16-KB-Seiten Gate']);
M([62,'block:1819','MUST','UX','PHASE-09','PHASE-09','UT-AND-EDGE-001','Edge-to-edge | SystemBars + CSS safe areas; keine abgeschnittenen Buttons unter Status-/Navigationsbar.','Edge-to-edge: SystemBars + CSS safe areas; keine abgeschnittenen Buttons unter Status-/Navigationsbar.','','Edge-to-edge Safe Areas']);
M([62,'block:1819','SHOULD','UX','PHASE-09','PHASE-09','UT-AND-ORIENT-001','Orientierung | Landscape-Präferenz auf Telefon; resizable/adaptive für Tablets, Foldables, Desktop Windows. Kein dauerhaftes Opt-out.','Landscape-Präferenz auf Telefon; resizable/adaptive für Tablets, Foldables, Desktop Windows; kein dauerhaftes Opt-out.','','Android Orientierung adaptiv']);
M([62,'block:1819','MUST','UX','PHASE-09','PHASE-09','UT-AND-BACK-001','Back | Predictive/gesture back durch Capacitor App Adapter und Navigationsstack; keine App-interne Fake-Systemgeste.','Predictive/gesture back durch Capacitor App Adapter und Navigationsstack; keine App-interne Fake-Systemgeste.','','Android Predictive Back']);
M([62,'block:1819','MUST_NOT','Save','PHASE-12','PHASE-12','UT-AND-BACKUP-001','Backup | android:allowBackup=false und DataExtractionRules schließen Saves aus Cloud-/Device-Transfer aus; manueller Export vorhanden.','android:allowBackup=false und DataExtractionRules schließen Saves aus Cloud-/Device-Transfer aus; manueller Export ist vorhanden.','','Android Backup deaktiviert']);
M([62,'block:1819','MUST_NOT','Android','PHASE-10','PHASE-10','UT-AND-PERMS-001','Permissions | Keine gefährlichen Permissions; INTERNET im Production Manifest entfernt.','Keine gefährlichen Permissions; INTERNET im Production Manifest entfernt.','','Android Permissions minimal']);
M([62,'block:1822','MUST','Store','PHASE-10','PHASE-10','UT-AND-PLAYDECL-001','Play-Console-Deklarationen | Spiel, Einmalkauf, Data Safety keine Erhebung, keine Ads, kein Login, Fantasygewalt stilisiert, allgemeines Publikum.','Play-Console-Deklarationen: Spiel, Einmalkauf, Data Safety keine Erhebung, keine Ads, kein Login, Fantasygewalt stilisiert, allgemeines Publikum.','','Play-Console-Deklarationen']);
M([62,'block:1825','MUST','QA','PHASE-20','PHASE-20','UT-AND-CERTMATRIX-001','Android Store-Cert-Testmatrix: Install/Update, Launch/Resume, Back/Gesture, Rotation/Fold/Resize, Notch, Offline, Audio, Performance, Accessibility, 16 KB, Pre-launch, Vitals Ziel <0,2% Crash, <0,1% ANR.','Android Store-Cert-Testmatrix wird vollständig durchlaufen: Install/Update, Launch/Resume, Back/Gesture, Rotation/Fold/Resize, Notch, Offline, Audio, Performance, Accessibility, 16 KB, Pre-launch, Vitals Ziel Crash <0,2% und ANR <0,1%.','pct|max:0.2','Android Store-Cert-Matrix']);
M([62,'block:1833','MUST','Store','PHASE-10','PHASE-10','UT-AND-RELEASE-001','Veröffentlichungsschritte: Play-Developerkonto, internen Track, ggf. geschlossener Test, Data Safety, Production Access, gestaffelter Rollout 10% -> 25% -> 50% -> 100%.','Android-Veröffentlichung folgt: Play-Developerkonto, interner Track, ggf. geschlossener Test, Data Safety, Production Access, gestaffelter Rollout 10%->25%->50%->100% nur wenn Vitals und Bewertungen keine Blocker zeigen.','','Android Veröffentlichungsschritte']);

// === CH 63 ===
M([63,'block:1836','MUST','iOS','PHASE-05','PHASE-05','UT-IOS-TOOLCHAIN-001','Toolchain | Xcode 26 oder höher, iOS/iPadOS 26 SDK für Upload; Capacitor 8 SPM-Projekt.','Toolchain: Xcode 26 oder höher, iOS/iPadOS 26 SDK für Upload; Capacitor 8 SPM-Projekt.','','iOS Toolchain']);
M([63,'block:1836','MUST','iOS','PHASE-05','PHASE-05','UT-IOS-DEPLOY-001','Deployment Target | iOS 15.0.','Deployment Target ist iOS 15.0.','ios|min:15','iOS Deployment Target 15']);
M([63,'block:1836','MUST','iOS','PHASE-05','PHASE-05','UT-IOS-DEVICE-001','Devices | iPhone und iPad Universal App; Landscape primär, adaptive Split/Stage-Manager-Layouts.','iPhone und iPad Universal App; Landscape primär, adaptive Split/Stage-Manager-Layouts.','','iOS Universal App']);
M([63,'block:1836','MUST','iOS','PHASE-05','PHASE-05','UT-IOS-BUNDLE-001','Bundle | com.ceegore.riftwarden; Version/Build strikt aufsteigend.','Bundle-ID com.ceegore.riftwarden; Version/Build strikt aufsteigend.','','iOS Bundle-ID']);
M([63,'block:1836','MUST','iOS','PHASE-09','PHASE-09','UT-IOS-AUDIO-001','Audio | AVAudioSession ambient, Background Audio Capability aus.','AVAudioSession ambient, Background Audio Capability aus.','','iOS Audio Session']);
M([63,'block:1836','MUST','Save','PHASE-12','PHASE-12','UT-IOS-FILES-001','Files | Application Support für Saves, excludeFromBackup=true; UIDocumentPicker für Transfer.','Application Support für Saves, excludeFromBackup=true; UIDocumentPicker für Transfer.','','iOS Files']);
M([63,'block:1836','MUST','Security','PHASE-10','PHASE-10','UT-IOS-PRIVACY-001','Privacy Manifest | PrivacyInfo.xcprivacy im App-Target und alle SDK-Manifeste prüfen; Approved Reasons dokumentieren.','PrivacyInfo.xcprivacy im App-Target und alle SDK-Manifeste werden geprüft; Approved Reasons werden dokumentiert.','','iOS Privacy Manifest']);
M([63,'block:1836','MUST_NOT','Security','PHASE-10','PHASE-10','UT-IOS-NET-001','Network | Keine ATS-Ausnahmen, keine Remote Endpoints, keine Tracking-Domains.','Keine ATS-Ausnahmen, keine Remote Endpoints, keine Tracking-Domains.','','iOS Network minimal']);
M([63,'block:1836','MUST_NOT','iOS','PHASE-10','PHASE-10','UT-IOS-ENTITLE-001','Entitlements | Keine Game Center, iCloud, Push, Sign in with Apple oder Background Modes in V1.','Keine Game Center, iCloud, Push, Sign in with Apple oder Background Modes in V1.','','iOS Entitlements minimal']);
M([63,'block:1839','MUST','Store','PHASE-10','PHASE-10','UT-IOS-ASCDECL-001','App-Store-Connect-Deklarationen: Data Not Collected, Age Rating Fantasy Violence: infrequent/mild nach tatsächlicher Darstellung; Paid App; vollständige Review Notes; öffentliche Support- und Privacy-URLs; EU Traderstatus.','App-Store-Connect-Deklarationen: Data Not Collected; Age Rating Fantasy Violence infrequent/mild; Paid App ohne IAP; vollständige Review Notes mit Offline-Hinweis; öffentliche Support- und Privacy-URLs; EU Traderstatus vor Veröffentlichung bestätigt.','','iOS ASC-Deklarationen']);
M([63,'block:1842','MUST','QA','PHASE-20','PHASE-20','UT-IOS-CERTMATRIX-001','iOS Store-Cert-Testmatrix: Install/Upgrade, Lifecycle, Orientation/Multitasking, Safe Areas, Audio, Accessibility, Review Completeness, Privacy, Energy.','iOS Store-Cert-Testmatrix wird vollständig durchlaufen: Install/Upgrade, Lifecycle, Orientation/Multitasking, Safe Areas, Audio, Accessibility, Review Completeness, Privacy, Energy.','','iOS Store-Cert-Matrix']);

// Write output
const out={schemaVersion:'1.0',chunk:'c',chapterRange:{lo:59,hi:87},requirements:R,contextOnly:X};
const path='docs/requirements/requirements/_staging/chunk-c.json';
import {mkdir as mk} from 'node:fs/promises';
import {dirname as dn} from 'node:path';
await mk(dn(path),{recursive:true});
await writeFile(path,JSON.stringify(out,null,2)+'\n','utf8');
console.log('Wrote',path,'with',R.length,'requirements');