// Build chunk-j.json with normative requirements from chapters 36-41
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';

function h(text) {
  return `sha256:${createHash('sha256').update(text).digest('hex')}`;
}

const chunk = {
  schemaVersion: '1.0',
  chunk: 'j',
  chapterRange: { lo: 36, hi: 41 },
  requirements: [
    // ===== Chapter 36 — UX für Formation, Vorschau und Kampf =====
    {
      id: 'REQ-TEMP-J-0001',
      title: 'Formationsscreen zeigt eigene 3x3-Formation und vollständige Gegnerformation als spiegelnde Vorschau.',
      statement: 'Der Formationsscreen zeigt links/oben die eigene 3x3-Formation und rechts/unten die vollständige Gegnerformation als spiegelnde Vorschau.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1376',
        quoteHash: h('Links/oben eigene 3x3-Formation, rechts/unten vollständige Gegnerformation als spiegelnde Vorschau.'),
        originalExcerpt: 'Links/oben eigene 3x3-Formation, rechts/unten vollständige Gegnerformation als spiegelnde Vorschau.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-FORMATION-LAYOUT-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0002',
      title: 'Drag-and-drop und Tap-Select/Tap-Place sind gleichwertig; ungültige Felder zeigen Grund direkt.',
      statement: 'Drag-and-drop und Tap-Select/Tap-Place sind als Eingabemethoden gleichwertig. Ungültige Felder zeigen ihren Grund direkt an.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1377',
        quoteHash: h('Drag-and-drop und Tap-Select/Tap-Place sind gleichwertig. Ungültige Felder zeigen Grund direkt.'),
        originalExcerpt: 'Drag-and-drop und Tap-Select/Tap-Place sind gleichwertig. Ungültige Felder zeigen Grund direkt.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-FORMATION-INPUT-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0003',
      title: 'Jede Karte zeigt Portrait, Rolle, Merkmale, LP/Angriff/Verteidigungskurzwerte, Kit/Ausrüstung und eine wichtige Fähigkeit.',
      statement: 'Jede Karte zeigt Portrait, Rolle, Merkmale, LP/Angriff/Verteidigungskurzwerte, Kit/Ausrüstung und eine wichtige Fähigkeit.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1378',
        quoteHash: h('Jede Karte zeigt Portrait, Rolle, Merkmale, LP/Angriff/Verteidigungskurzwerte, Kit/Ausrüstung und wichtige Fähigkeit.'),
        originalExcerpt: 'Jede Karte zeigt Portrait, Rolle, Merkmale, LP/Angriff/Verteidigungskurzwerte, Kit/Ausrüstung und wichtige Fähigkeit.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-CARD-CONTENT-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0004',
      title: 'Reichweitenvorschau wird als horizontales Band dargestellt; Bahnwechseloptionen erscheinen als Pfeile.',
      statement: 'Beim Auswählen einer Einheit wird die Reichweitenvorschau als horizontales Band dargestellt und Bahnwechseloptionen werden als Pfeile angezeigt.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1379',
        quoteHash: h('Reichweitenvorschau wird beim Auswählen als horizontales Band dargestellt; Bahnwechseloptionen als Pfeile.'),
        originalExcerpt: 'Reichweitenvorschau wird beim Auswählen als horizontales Band dargestellt; Bahnwechseloptionen als Pfeile.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-RANGE-PREVIEW-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0005',
      title: 'Aktive Synergien und Doktrinwirkung aktualisieren sofort; Beinahe-Synergie zeigt „2/3“, aber kein aufdringliches Warnsignal.',
      statement: 'Aktive Synergien und die Doktrinwirkung aktualisieren sofort. Eine Beinahe-Synergie wird als „2/3“ dargestellt, aber ohne aufdringliches Warnsignal.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1380',
        quoteHash: h('Aktive Synergien und Doktrinwirkung aktualisieren sofort. Beinahe-Synergie zeigt „2/3“, aber kein aufdringliches Warnsignal.'),
        originalExcerpt: 'Aktive Synergien und Doktrinwirkung aktualisieren sofort. Beinahe-Synergie zeigt „2/3“, aber kein aufdringliches Warnsignal.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SYNERGY-FEEDBACK-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0006',
      title: 'Gegnerkarte zeigt Rolle, Startfeld, Angriffstyp, Fähigkeitstrigger, Elite/Championstatus, Beschwörungen und natürliche Gegenstrategien.',
      statement: 'Die Gegnerkarte zeigt Rolle, Startfeld, Angriffstyp, Fähigkeitstrigger, Elite-/Championstatus, Beschwörungen und natürliche Gegenstrategien.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1381',
        quoteHash: h('Gegnerkarte enthält Rolle, Startfeld, Angriffstyp, Fähigkeitstrigger, Elite/Championstatus, Beschwörungen und natürliche Gegenstrategien.'),
        originalExcerpt: 'Gegnerkarte enthält Rolle, Startfeld, Angriffstyp, Fähigkeitstrigger, Elite/Championstatus, Beschwörungen und natürliche Gegenstrategien.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-ENEMY-CARD-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0007',
      title: 'Bossvorschau besitzt eigene Phasentabs und listet Rang- und Schwierigkeitszusätze getrennt.',
      statement: 'Die Bossvorschau besitzt eigene Phasentabs und listet Rang- und Schwierigkeitszusätze getrennt auf.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1382',
        quoteHash: h('Bossvorschau besitzt eigene Phasentabs und listet Rang-/Schwierigkeitszusätze getrennt.'),
        originalExcerpt: 'Bossvorschau besitzt eigene Phasentabs und listet Rang-/Schwierigkeitszusätze getrennt.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-BOSS-PREVIEW-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0008',
      title: 'Startbutton bleibt erreichbar; harte Regelverstöße blockieren, weiche Risiken erzeugen einmalige Warnung.',
      statement: 'Der Startbutton bleibt erreichbar. Harte Regelverstöße blockieren den Start; weiche Risiken erzeugen genau einmal eine Warnung.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.1 Formationsscreen',
        locator: 'block:1383',
        quoteHash: h('Startbutton bleibt erreichbar, aber harte Regelverstöße blockieren; weiche Risiken erzeugen einmalige Warnung.'),
        originalExcerpt: 'Startbutton bleibt erreichbar, aber harte Regelverstöße blockieren; weiche Risiken erzeugen einmalige Warnung.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-START-GATE-036'] }],
      numericConstraints: [{ kind: 'exact', name: 'softWarningPerSession', value: 1 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0009',
      title: 'Spieler kann jederzeit pausieren und Einheiten antippen, um Werte, Ziel, Ladung und aktive Effekte zu lesen.',
      statement: 'Der Spieler kann den Kampf jederzeit pausieren und Einheiten antippen, um Werte, Ziel, Ladung und aktive Effekte zu lesen.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.2 Kampfbildschirm',
        locator: 'block:1384',
        quoteHash: h('Der Spieler kann jederzeit pausieren und Einheiten antippen, um Werte, Ziel, Ladung und aktive Effekte zu lesen.'),
        originalExcerpt: 'Der Spieler kann jederzeit pausieren und Einheiten antippen, um Werte, Ziel, Ladung und aktive Effekte zu lesen.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-COMBAT-INSPECT-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0010',
      title: 'Spieler darf im Kampf niemals Ziel markieren, Fähigkeit auslösen, Doktrin ändern, Gegenstand verwenden oder Verstärkung rufen.',
      statement: 'Der Spieler darf im Kampf niemals Ziel markieren, Fähigkeit auslösen, Doktrin ändern, Gegenstand verwenden oder Verstärkung rufen.',
      norm: 'MUST_NOT',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.2 Kampfbildschirm',
        locator: 'block:1385',
        quoteHash: h('Der Spieler kann niemals Ziel markieren, Fähigkeit auslösen, Doktrin ändern, Gegenstand verwenden oder Verstärkung rufen.'),
        originalExcerpt: 'Der Spieler kann niemals Ziel markieren, Fähigkeit auslösen, Doktrin ändern, Gegenstand verwenden oder Verstärkung rufen.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-COMBAT-NO-INPUT-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0011',
      title: 'Wichtige Signaturfähigkeit verlangsamt bei 2x/3x auf maximal 1,2 reale Sekunden auf 1x; Option deaktivierbar.',
      statement: 'Eine wichtige Signaturfähigkeit verlangsamt bei 2x- oder 3x-Geschwindigkeit für maximal 1,2 reale Sekunden auf 1x. Diese Option muss deaktivierbar sein.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.2 Kampfbildschirm',
        locator: 'block:1386',
        quoteHash: h('Wichtige Signaturfähigkeit kann bei 2x/3x automatisch für maximal 1,2 reale Sekunden auf 1x verlangsamen. Option deaktivierbar.'),
        originalExcerpt: 'Wichtige Signaturfähigkeit kann bei 2x/3x automatisch für maximal 1,2 reale Sekunden auf 1x verlangsamen. Option deaktivierbar.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SIG-SLOW-036'] }],
      numericConstraints: [{ kind: 'max', name: 'signatureSlowdownRealSeconds', value: 1.2 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0012',
      title: 'Schadenszahlen werden bei mehr als vier Treffern in 0,4 s auf dasselbe Ziel aggregiert; Detail bleibt im Log.',
      statement: 'Schadenszahlen werden aggregiert, wenn mehr als vier Treffer in 0,4 s auf dasselbe Ziel fallen; das Detail bleibt im Log erhalten.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.2 Kampfbildschirm',
        locator: 'block:1387',
        quoteHash: h('Schadenszahlen werden aggregiert, wenn mehr als vier Treffer in 0,4 s auf dasselbe Ziel fallen; Detail bleibt im Log.'),
        originalExcerpt: 'Schadenszahlen werden aggregiert, wenn mehr als vier Treffer in 0,4 s auf dasselbe Ziel fallen; Detail bleibt im Log.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-DAMAGE-AGG-036'] }],
      numericConstraints: [
        { kind: 'min', name: 'aggHitsThreshold', value: 4 },
        { kind: 'max', name: 'aggWindowSeconds', value: 0.4 },
      ],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0013',
      title: 'Kamera bleibt standardmäßig vollständig auf allen drei Bahnen; kurzer Bossphasenzoom nur, wenn keine aktive Gefahrenwarnung verdeckt wird.',
      statement: 'Die Kamera bleibt standardmäßig vollständig auf allen drei Bahnen. Ein kurzer Zoom auf eine Bossphase erfolgt nur, wenn dadurch keine aktive Gefahrenwarnung verdeckt wird.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.2 Kampfbildschirm',
        locator: 'block:1388',
        quoteHash: h('Kamera bleibt standardmäßig vollständig auf allen drei Bahnen. Kurzer Zoom auf Bossphase nur, wenn keine aktive Gefahrenwarnung verdeckt wird.'),
        originalExcerpt: 'Kamera bleibt standardmäßig vollständig auf allen drei Bahnen. Kurzer Zoom auf Bossphase nur, wenn keine aktive Gefahrenwarnung verdeckt wird.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-CAMERA-LANE-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0014',
      title: 'Ergebnis-Flow-Reihenfolge: Sieg/Niederlage → Bewertung → 3 wichtigste Beiträge → bis 2 Hinweise → detaillierte Statistik optional → Belohnungswahl → Karte.',
      statement: 'Der Ergebnis- und Belohnungsflow folgt strikt der Reihenfolge: Sieg/Niederlage, Bewertung, die 3 wichtigsten Beiträge, bis zu 2 Hinweise, detaillierte Statistik optional, Belohnungswahl, Karte.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.3 Ergebnis- und Belohnungsflow',
        locator: 'block:1389',
        quoteHash: h('Reihenfolge: Sieg/Niederlage -> Bewertung -> 3 wichtigste Beiträge -> bis 2 Hinweise -> detaillierte Statistik optional -> Belohnungswahl -> Karte.'),
        originalExcerpt: 'Reihenfolge: Sieg/Niederlage -> Bewertung -> 3 wichtigste Beiträge -> bis 2 Hinweise -> detaillierte Statistik optional -> Belohnungswahl -> Karte.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-RESULT-FLOW-036'] }],
      numericConstraints: [
        { kind: 'exact', name: 'topContributionCount', value: 3 },
        { kind: 'max', name: 'hintCount', value: 2 },
      ],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0015',
      title: 'Wiederholen eines Bosskampfs vom Anker ist mit höchstens zwei Eingaben möglich.',
      statement: 'Das Wiederholen eines Bosskampfs vom Anker aus darf höchstens zwei Eingaben erfordern.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.3 Ergebnis- und Belohnungsflow',
        locator: 'block:1390',
        quoteHash: h('Wiederholen eines Bosskampfs vom Anker ist mit höchstens zwei Eingaben möglich.'),
        originalExcerpt: 'Wiederholen eines Bosskampfs vom Anker ist mit höchstens zwei Eingaben möglich.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-BOSS-RETRY-036'] }],
      numericConstraints: [{ kind: 'max', name: 'bossRetryInputs', value: 2 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0016',
      title: 'Neue Kodex-/Meisterschaftsfortschritte erscheinen kompakt nach der Belohnung und blockieren nicht mehrere Sekunden pro Eintrag.',
      statement: 'Neue Kodex- und Meisterschaftsfortschritte erscheinen kompakt nach der Belohnung und blockieren den Ablauf nicht mehrere Sekunden pro Eintrag.',
      norm: 'MUST_NOT',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.3 Ergebnis- und Belohnungsflow',
        locator: 'block:1391',
        quoteHash: h('Neue Kodex-/Meisterschaftsfortschritte erscheinen kompakt nach der Belohnung und blockieren nicht mehrere Sekunden pro Eintrag.'),
        originalExcerpt: 'Neue Kodex-/Meisterschaftsfortschritte erscheinen kompakt nach der Belohnung und blockieren nicht mehrere Sekunden pro Eintrag.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-CODEX-NOBLOCK-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0017',
      title: 'Belohnungskarten zeigen aktuellen Bestand, Synergie/Kompatibilität und genaue Auswirkung vor der Wahl.',
      statement: 'Belohnungskarten zeigen vor der Wahl den aktuellen Bestand, Synergie/Kompatibilität und die genaue Auswirkung.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 36,
        section: '36.3 Ergebnis- und Belohnungsflow',
        locator: 'block:1392',
        quoteHash: h('Belohnungskarten zeigen aktuellen Bestand, Synergie/Kompatibilität und genaue Auswirkung vor Wahl.'),
        originalExcerpt: 'Belohnungskarten zeigen aktuellen Bestand, Synergie/Kompatibilität und genaue Auswirkung vor Wahl.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-LOOT-CARD-036'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },

    // ===== Chapter 37 — Visuelle Ausrichtung =====
    {
      id: 'REQ-TEMP-J-0018',
      title: 'Visuelle Ausrichtung: stilisierte Fantasy mit klaren 2D/2.5D-Silhouetten; Spiel wirkt nicht wie generischer Browser-Autobattler, Asset-Sammlung oder UI-lastiges Idle-Spiel.',
      statement: 'Das Spiel verfolgt eine stilisierte, hochwertige Fantasy-Optik mit klaren 2D-/2.5D-Silhouetten, kräftigen Formen und kontrollierter Effektmenge. Es darf nicht wie ein generischer Browser-Autobattler, eine Asset-Sammlung oder ein UI-lastiges Idle-Spiel wirken.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37. Visuelle Ausrichtung',
        locator: 'block:1405',
        quoteHash: h('Ziel ist stilisierte, hochwertige Fantasy mit klaren 2D/2.5D-Silhouetten, kräftigen Formen und kontrollierter Effektmenge. Das Spiel darf nicht wie ein generischer Browser-Autobattler, eine Asset-Sammlung oder ein UI-lastiges Idle-Spiel wirken.'),
        originalExcerpt: 'Ziel ist stilisierte, hochwertige Fantasy mit klaren 2D/2.5D-Silhouetten, kräftigen Formen und kontrollierter Effektmenge. Das Spiel darf nicht wie ein generischer Browser-Autobattler, eine Asset-Sammlung oder ein UI-lastiges Idle-Spiel wirken.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-ART-DIRECTION-037'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0019',
      title: 'Jeder Held ist in schwarzer Silhouette bei 96 px Höhe eindeutig identifizierbar.',
      statement: 'Jeder Held muss in schwarzer Silhouette bei 96 px Höhe eindeutig identifizierbar sein.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37.1 Silhouetten- und Lesbarkeitstest',
        locator: 'block:1406',
        quoteHash: h('Jeder Held ist in schwarzer Silhouette bei 96 px Höhe eindeutig identifizierbar.'),
        originalExcerpt: 'Jeder Held ist in schwarzer Silhouette bei 96 px Höhe eindeutig identifizierbar.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SILHOUETTE-HERO-037'] }],
      numericConstraints: [{ kind: 'exact', name: 'heroSilhouetteHeightPx', value: 96 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0020',
      title: 'Jede Truppenrolle ist bei 64 px grob erkennbar: Schild, Speer, Bogen, Stab, Banner, Werkzeug.',
      statement: 'Jede Truppenrolle muss bei 64 px grob erkennbar sein: Schild, Speer, Bogen, Stab, Banner, Werkzeug.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37.1 Silhouetten- und Lesbarkeitstest',
        locator: 'block:1407',
        quoteHash: h('Jede Truppenrolle ist bei 64 px grob erkennbar: Schild, Speer, Bogen, Stab, Banner, Werkzeug.'),
        originalExcerpt: 'Jede Truppenrolle ist bei 64 px grob erkennbar: Schild, Speer, Bogen, Stab, Banner, Werkzeug.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SILHOUETTE-TROOP-037'] }],
      numericConstraints: [{ kind: 'exact', name: 'troopSilhouetteHeightPx', value: 64 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0021',
      title: 'Bossphasen ändern mindestens ein großes Formelement oder Arenaelement, nicht nur Farbe.',
      statement: 'Bossphasen müssen mindestens ein großes Formelement oder ein Arenaelement ändern, nicht nur die Farbe.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37.1 Silhouetten- und Lesbarkeitstest',
        locator: 'block:1408',
        quoteHash: h('Bossphasen ändern mindestens ein großes Formelement oder Arenaelement, nicht nur Farbe.'),
        originalExcerpt: 'Bossphasen ändern mindestens ein großes Formelement oder Arenaelement, nicht nur Farbe.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-BOSS-PHASE-VIS-037'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0022',
      title: 'Beschwörungen unterscheiden sich durch Körperform und Besitzer-Rune; keine zwei Kategorien verwenden dieselbe Silhouette.',
      statement: 'Beschwörungen müssen sich durch Körperform und Besitzer-Rune unterscheiden; keine zwei Kategorien verwenden dieselbe Silhouette.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37.1 Silhouetten- und Lesbarkeitstest',
        locator: 'block:1409',
        quoteHash: h('Beschwörungen unterscheiden sich durch Körperform und Besitzer-Rune; keine zwei Kategorien verwenden dieselbe Silhouette.'),
        originalExcerpt: 'Beschwörungen unterscheiden sich durch Körperform und Besitzer-Rune; keine zwei Kategorien verwenden dieselbe Silhouette.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SUMMON-DISTINCT-037'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0023',
      title: 'Warnflächen besitzen Rand, Muster und Symbol; Farbe allein ist nie die einzige Information.',
      statement: 'Warnflächen müssen Rand, Muster und Symbol besitzen; Farbe allein darf nie die einzige Information sein.',
      norm: 'MUST_NOT',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 37,
        section: '37.1 Silhouetten- und Lesbarkeitstest',
        locator: 'block:1410',
        quoteHash: h('Warnflächen besitzen Rand, Muster und Symbol. Farbe allein ist nie die einzige Information.'),
        originalExcerpt: 'Warnflächen besitzen Rand, Muster und Symbol. Farbe allein ist nie die einzige Information.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-WARN-SHAPE-037'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },

    // ===== Chapter 38 — Kampfpolish und Feedbackbudget =====
    {
      id: 'REQ-TEMP-J-0024',
      title: 'Maximal zwei starke Kameraschüttler innerhalb 1 Sekunde; weitere werden gedämpft.',
      statement: 'Innerhalb von 1 Sekunde dürfen maximal zwei starke Kameraschüttler auftreten; weitere werden gedämpft.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 38,
        section: '38. Kampfpolish und Feedbackbudget',
        locator: 'block:1418',
        quoteHash: h('Maximal zwei starke Kameraschüttler innerhalb 1 Sekunde; weitere werden gedämpft.'),
        originalExcerpt: 'Maximal zwei starke Kameraschüttler innerhalb 1 Sekunde; weitere werden gedämpft.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SHAKE-BUDGET-038'] }],
      numericConstraints: [
        { kind: 'max', name: 'strongShakesPerSecond', value: 2 },
        { kind: 'exact', name: 'shakeWindowSeconds', value: 1 },
      ],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0025',
      title: 'Maximal drei große Vollflächen-Partikelsysteme gleichzeitig; weitere verwenden reduzierte Variante.',
      statement: 'Gleichzeitig dürfen maximal drei große Vollflächen-Partikelsysteme aktiv sein; weitere verwenden eine reduzierte Variante.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 38,
        section: '38. Kampfpolish und Feedbackbudget',
        locator: 'block:1419',
        quoteHash: h('Maximal drei große Vollflächen-Partikelsysteme gleichzeitig; weitere verwenden reduzierte Variante.'),
        originalExcerpt: 'Maximal drei große Vollflächen-Partikelsysteme gleichzeitig; weitere verwenden reduzierte Variante.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-PARTICLE-BUDGET-038'] }],
      numericConstraints: [{ kind: 'max', name: 'largeParticleSystems', value: 3 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0026',
      title: 'Trefferfeedback muss bei 3x noch lesbar, aber nicht als Stroboskop wirken.',
      statement: 'Trefferfeedback muss bei 3x-Geschwindigkeit noch lesbar sein, darf aber nicht als Stroboskop wirken.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 38,
        section: '38. Kampfpolish und Feedbackbudget',
        locator: 'block:1420',
        quoteHash: h('Trefferfeedback muss bei 3x noch lesbar, aber nicht als Stroboskop wirken.'),
        originalExcerpt: 'Trefferfeedback muss bei 3x noch lesbar, aber nicht als Stroboskop wirken.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-HIT-LEGIBILITY-038'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0027',
      title: 'Reduzierte-Effekte-Modus senkt Partikelzahl mindestens 60%, entfernt Schütteln und Blitze, behält Warnformen.',
      statement: 'Im Reduzierte-Effekte-Modus wird die Partikelzahl um mindestens 60 % gesenkt, Schütteln und Blitze werden entfernt, Warnformen bleiben erhalten.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 38,
        section: '38. Kampfpolish und Feedbackbudget',
        locator: 'block:1421',
        quoteHash: h('Reduzierte-Effekte-Modus senkt Partikelzahl mindestens 60%, entfernt Schütteln und Blitze, behält Warnformen.'),
        originalExcerpt: 'Reduzierte-Effekte-Modus senkt Partikelzahl mindestens 60%, entfernt Schütteln und Blitze, behält Warnformen.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-REDUCED-FX-038'] }],
      numericConstraints: [{ kind: 'min', name: 'reducedFxParticleCutPercent', value: 60 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },

    // ===== Chapter 39 — Audioausrichtung =====
    {
      id: 'REQ-TEMP-J-0028',
      title: 'Separate Audio-Regler: Gesamt, Musik, Effekte, Stimmen; Stummoption je Kanal.',
      statement: 'Es gibt separate Audio-Regler für Gesamt, Musik, Effekte und Stimmen mit einer Stummoption je Kanal.',
      norm: 'MUST',
      category: 'A11y',
      source: {
        sourceId: 'gdd-v5',
        chapter: 39,
        section: '39. Audioausrichtung',
        locator: 'block:1426',
        quoteHash: h('Separate Regler: Gesamt, Musik, Effekte, Stimmen; Stummoption je Kanal.'),
        originalExcerpt: 'Separate Regler: Gesamt, Musik, Effekte, Stimmen; Stummoption je Kanal.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-AUDIO-MIX-039'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0029',
      title: 'Untertitel für alle gesprochenen Inhalte; Sprechername und optionaler Richtungsindikator.',
      statement: 'Für alle gesprochenen Inhalte sind Untertitel vorhanden; jede Zeile enthält den Sprechernamen und optional einen Richtungsindikator.',
      norm: 'MUST',
      category: 'A11y',
      source: {
        sourceId: 'gdd-v5',
        chapter: 39,
        section: '39. Audioausrichtung',
        locator: 'block:1427',
        quoteHash: h('Untertitel für alle gesprochenen Inhalte; Sprechername und optional Richtungsindikator.'),
        originalExcerpt: 'Untertitel für alle gesprochenen Inhalte; Sprechername und optional Richtungsindikator.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-SUBTITLES-039'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0030',
      title: 'Gameplayrelevante Audiohinweise besitzen immer ein visuelles Äquivalent.',
      statement: 'Jeder gameplayrelevante Audiohinweis besitzt immer auch ein visuelles Äquivalent.',
      norm: 'MUST',
      category: 'A11y',
      source: {
        sourceId: 'gdd-v5',
        chapter: 39,
        section: '39. Audioausrichtung',
        locator: 'block:1428',
        quoteHash: h('Gameplayrelevante Audiohinweise besitzen immer visuelles Äquivalent.'),
        originalExcerpt: 'Gameplayrelevante Audiohinweise besitzen immer visuelles Äquivalent.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-AUDIO-VISUAL-039'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0031',
      title: 'Keine realistischen Todesschreie; Falllaute stilisiert und kurz.',
      statement: 'Es gibt keine realistischen Todesschreie; Falllaute sind stilisiert und kurz.',
      norm: 'MUST_NOT',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 39,
        section: '39. Audioausrichtung',
        locator: 'block:1429',
        quoteHash: h('Keine realistischen Todesschreie; Falllaute stilisiert und kurz.'),
        originalExcerpt: 'Keine realistischen Todesschreie; Falllaute stilisiert und kurz.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-DEATH-AUDIO-039'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },

    // ===== Chapter 40 — Bedienung, Komfort und Barrierefreiheit =====
    {
      id: 'REQ-TEMP-J-0032',
      title: 'Kurztooltips verwenden maximal 220 Zeichen; Detailansicht darf exakte Zahlen und Regeln enthalten.',
      statement: 'Kurztooltips verwenden maximal 220 Zeichen. Die Detailansicht darf exakte Zahlen und Regeln enthalten.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 40,
        section: '40.1 Informationsdichte',
        locator: 'block:1435',
        quoteHash: h('Kurztooltips verwenden maximal 220 Zeichen; Detailansicht darf exakte Zahlen und Regeln enthalten.'),
        originalExcerpt: 'Kurztooltips verwenden maximal 220 Zeichen; Detailansicht darf exakte Zahlen und Regeln enthalten.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-TOOLTIP-LEN-040'] }],
      numericConstraints: [{ kind: 'max', name: 'shortTooltipChars', value: 220 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0033',
      title: 'Wichtige Begriffe sind antippbar und öffnen Glossar ohne Verlust der aktuellen Vorbereitung.',
      statement: 'Wichtige Begriffe sind antippbar und öffnen das Glossar, ohne dass die aktuelle Vorbereitung verloren geht.',
      norm: 'MUST',
      category: 'A11y',
      source: {
        sourceId: 'gdd-v5',
        chapter: 40,
        section: '40.1 Informationsdichte',
        locator: 'block:1436',
        quoteHash: h('Wichtige Begriffe sind antippbar und öffnen Glossar ohne Verlust der aktuellen Vorbereitung.'),
        originalExcerpt: 'Wichtige Begriffe sind antippbar und öffnen Glossar ohne Verlust der aktuellen Vorbereitung.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-GLOSSAR-LINK-040'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0034',
      title: 'Komplexe Bossphase verwendet höchstens vier Kernbulletpoints plus optionale Details.',
      statement: 'Eine komplexe Bossphase verwendet höchstens vier Kernbulletpoints plus optionale Details.',
      norm: 'MUST',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 40,
        section: '40.1 Informationsdichte',
        locator: 'block:1437',
        quoteHash: h('Komplexe Bossphase verwendet höchstens vier Kernbulletpoints plus optionale Details.'),
        originalExcerpt: 'Komplexe Bossphase verwendet höchstens vier Kernbulletpoints plus optionale Details.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-BOSS-BULLETS-040'] }],
      numericConstraints: [{ kind: 'max', name: 'bossPhaseKeyBullets', value: 4 }],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0035',
      title: 'Auf Telefon gibt es keine horizontale Scrollpflicht; Vergleichstabellen werden zu gestapelten Karten umgebaut.',
      statement: 'Auf Telefon gibt es keine horizontale Scrollpflicht. Vergleichstabellen werden in gestapelte Karten umgebaut.',
      norm: 'MUST_NOT',
      category: 'UX',
      source: {
        sourceId: 'gdd-v5',
        chapter: 40,
        section: '40.1 Informationsdichte',
        locator: 'block:1438',
        quoteHash: h('Keine horizontale Scrollpflicht auf Telefon. Vergleichstabellen werden in gestapelte Karten umgebaut.'),
        originalExcerpt: 'Keine horizontale Scrollpflicht auf Telefon. Vergleichstabellen werden in gestapelte Karten umgebaut.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-NO-HSCROLL-040'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0036',
      title: 'Alle Menüs sind mit Controller/Tastatur navigierbar, auch wenn Android-Touch primär ist.',
      statement: 'Alle Menüs sind mit Controller oder Tastatur navigierbar, auch wenn Android-Touch als primäre Eingabe dient.',
      norm: 'MUST',
      category: 'A11y',
      source: {
        sourceId: 'gdd-v5',
        chapter: 40,
        section: '40.1 Informationsdichte',
        locator: 'block:1439',
        quoteHash: h('Alle Menüs mit Controller/Tastatur navigierbar, auch wenn Android-Touch primär ist.'),
        originalExcerpt: 'Alle Menüs mit Controller/Tastatur navigierbar, auch wenn Android-Touch primär ist.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-CTRL-NAV-040'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },

    // ===== Chapter 41 — Inhaltliche Datenverträge =====
    {
      id: 'REQ-TEMP-J-0037',
      title: 'Inhaltsdaten sind validierte, versionierte JSON-Inhaltsdaten plus TypeScript-Schemas; jede Datenentität besitzt die geforderten semantischen Felder.',
      statement: 'Die technische Speicherform gemäß Version 4 sind validierte, versionierte JSON-Inhaltsdaten plus TypeScript-Schemas. Jede Datenentität muss mindestens die spezifizierten semantischen Felder besitzen.',
      norm: 'MUST',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41. Inhaltliche Datenverträge',
        locator: 'block:1446',
        quoteHash: h('Version 4 legt die technische Speicherform als validierte, versionierte JSON-Inhaltsdaten plus TypeScript-Schemas fest. Jede Datenentität muss mindestens die folgenden semantischen Felder besitzen. IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.'),
        originalExcerpt: 'Version 4 legt die technische Speicherform als validierte, versionierte JSON-Inhaltsdaten plus TypeScript-Schemas fest. Jede Datenentität muss mindestens die folgenden semantischen Felder besitzen. IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-DATA-CONTRACT-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0038',
      title: 'IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.',
      statement: 'IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.',
      norm: 'MUST',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41. Inhaltliche Datenverträge',
        locator: 'block:1446',
        quoteHash: h('IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.'),
        originalExcerpt: 'IDs sind stabile, kleingeschriebene ASCII-Schlüssel und dürfen nach Veröffentlichung nicht ohne explizite Migration umbenannt werden.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-ID-STABILITY-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0039',
      title: 'Stabile ID-Konvention: hero_<name>, troop_<rolle>, enemy_<name>, ability__; mission_<zone>_<idx>, event_; gear_main_, gear_talisman_, gear_kit_, gear_banner_.',
      statement: 'Helden-IDs folgen hero_<name> (z. B. hero_aurel, hero_mira), Truppen troop_<rolle> (z. B. troop_shieldguard), Gegner enemy_<name> (z. B. enemy_ash_soldier) und Fähigkeiten ability__<…>. Missionen folgen mission_<zone>_<idx> (mission_1_1 … mission_4_5), Ereignisse event_<…> und Gegenstände gear_main_<…>, gear_talisman_<…>, gear_kit_<…>, gear_banner_<…>.',
      norm: 'MUST',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41.1 Stabile ID-Konvention',
        locator: 'block:1447',
        quoteHash: h('Helden: hero_aurel, hero_mira usw.; Truppen: troop_shieldguard; Gegner: enemy_ash_soldier; Fähigkeiten: ability__.'),
        originalExcerpt: 'Helden: hero_aurel, hero_mira usw.; Truppen: troop_shieldguard; Gegner: enemy_ash_soldier; Fähigkeiten: ability__.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-ID-CONVENTION-HERO-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0040',
      title: 'Stabile ID-Konvention: Missionen mission_1_1 bis mission_4_5; Ereignisse event_; Gegenstände gear_main_, gear_talisman_, gear_kit_, gear_banner_.',
      statement: 'Missionen-IDs reichen von mission_1_1 bis mission_4_5, Ereignisse verwenden das Präfix event_, Gegenstände die Präfixe gear_main_, gear_talisman_, gear_kit_, gear_banner_.',
      norm: 'MUST',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41.1 Stabile ID-Konvention',
        locator: 'block:1448',
        quoteHash: h('Missionen: mission_1_1 bis mission_4_5; Ereignisse: event_; Gegenstände: gear_main_, gear_talisman_, gear_kit_, gear_banner_.'),
        originalExcerpt: 'Missionen: mission_1_1 bis mission_4_5; Ereignisse: event_; Gegenstände: gear_main_, gear_talisman_, gear_kit_, gear_banner_.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-ID-CONVENTION-MISSION-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0041',
      title: 'Lokalisierte Namen sind nie IDs und werden nicht für Savegame-Logik verwendet.',
      statement: 'Lokalisierte Namen sind niemals IDs und werden nicht für Savegame-Logik verwendet.',
      norm: 'MUST_NOT',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41.1 Stabile ID-Konvention',
        locator: 'block:1449',
        quoteHash: h('Lokalisierte Namen sind nie IDs und werden nicht für Savegame-Logik verwendet.'),
        originalExcerpt: 'Lokalisierte Namen sind nie IDs und werden nicht für Savegame-Logik verwendet.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-LOC-NAME-NOID-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
    {
      id: 'REQ-TEMP-J-0042',
      title: 'Alle Referenzen werden beim Build validiert; unbekannte ID ist harter Fehler, kein stilles Überspringen.',
      statement: 'Alle Referenzen werden beim Build validiert. Eine unbekannte ID ist ein harter Fehler und wird nicht stillschweigend übersprungen.',
      norm: 'MUST',
      category: 'Content',
      source: {
        sourceId: 'gdd-v5',
        chapter: 41,
        section: '41.1 Stabile ID-Konvention',
        locator: 'block:1450',
        quoteHash: h('Alle Referenzen werden beim Build validiert; unbekannte ID ist harter Fehler, kein stilles Überspringen.'),
        originalExcerpt: 'Alle Referenzen werden beim Build validiert; unbekannte ID ist harter Fehler, kein stilles Überspringen.',
      },
      ownerPhases: ['PHASE-00'],
      verification: [{ type: 'review', plannedPhase: 'PHASE-00', testIds: ['REV-REF-VALIDATION-041'] }],
      numericConstraints: [],
      relatedNormIds: [],
      relatedScreenIds: [],
      status: 'planned',
      notes: null,
    },
  ],
};

writeFileSync(
  'docs/requirements/requirements/_staging/chunk-j.json',
  `${JSON.stringify(chunk, null, 2)}\n`,
  'utf8',
);

console.log(`Wrote ${chunk.requirements.length} requirements to docs/requirements/requirements/_staging/chunk-j.json`);