import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs/promises";import path from "node:path";import os from "node:os";import { compileGraph } from "../../tools/content/lib/compiler-core.mjs";import { loadSource,loadLocaleKeys } from "../../tools/content/lib/source-loader.mjs";import { verifyManifest } from "../../tools/content/lib/manifest.mjs";import { starterRoot,tempCopy,readJson,writeJson } from "./test-helpers.mjs";
async function build(root,out,profile="fixture"){return compileGraph({root,outDir:out,profile,loadSource,loadLocaleKeys});}
async function tree(dir){const out={};for(const n of (await fs.readdir(dir)).sort()){out[n]=await fs.readFile(path.join(dir,n),"utf8");}return out;}
test("compiler builds manifest",async()=>{const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-build-"));const r=await build(starterRoot,o);assert.match(r.manifest.contentVersion,/^[a-f0-9]{64}$/);});
test("two builds byte identical",async()=>{const a=await fs.mkdtemp(path.join(os.tmpdir(),"p09-a-"));const b=await fs.mkdtemp(path.join(os.tmpdir(),"p09-b-"));await build(starterRoot,a);await build(starterRoot,b);assert.deepEqual(await tree(a),await tree(b));});
test("generated includes metadata header",async()=>{const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-h-"));await build(starterRoot,o);const u=JSON.parse(await fs.readFile(path.join(o,"unit.json")));assert.equal(u.generatedBy,"riftwarden-content-compiler-v1");});
test("seconds disappear in generated",async()=>{const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-t-"));await build(starterRoot,o);const text=await fs.readFile(path.join(o,"ability.json"),"utf8");assert.equal(text.includes("Seconds"),false);assert.equal(text.includes("castTicks"),true);});
test("manifest verifies",async()=>{const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-v-"));const r=await build(starterRoot,o);await assert.doesNotReject(()=>verifyManifest(o,r.manifest));});
test("release rejects fixture profile",async()=>{const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-r-"));await assert.rejects(()=>build(starterRoot,o,"release"),/P09_RELEASE_PROFILE/);});
test("generated cannot overlap source",async()=>await assert.rejects(()=>build(starterRoot,path.join(starterRoot,"content/source/generated")),/P09_GENERATED_SOURCE_OVERWRITE/));
test("entity order stable by ID",async()=>{const r=await tempCopy();const u=await readJson(r,"content/source/units/units.json");u.entities.reverse();await writeJson(r,"content/source/units/units.json",u);const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-sort-"));await build(r,o);const g=JSON.parse(await fs.readFile(path.join(o,"unit.json")));assert.deepEqual(g.entities.map((x)=>x.id),["enemy_fixture_echo","hero_fixture_warden"]);});
