import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs/promises";import path from "node:path";import os from "node:os";import { compileGraph } from "../../tools/content/lib/compiler-core.mjs";import { loadSource,loadLocaleKeys } from "../../tools/content/lib/source-loader.mjs";import { loadVerifiedBundle } from "../../tools/content/lib/runtime-core.mjs";import { starterRoot } from "./test-helpers.mjs";
async function built(){const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-runtime-"));await compileGraph({root:starterRoot,outDir:o,profile:"fixture",loadSource,loadLocaleKeys});return o;}
test("verified runtime loads atomically",async()=>{const b=await loadVerifiedBundle(await built());assert.equal(b.byType.get("unit").size,2);});
test("entities deep frozen",async()=>{const b=await loadVerifiedBundle(await built());const e=b.byType.get("unit").get("hero_fixture_warden");assert.equal(Object.isFrozen(e),true);assert.equal(Object.isFrozen(e.baseStats),true);});
test("stable map insertion order",async()=>{const b=await loadVerifiedBundle(await built());assert.deepEqual([...b.byType.get("unit").keys()],["enemy_fixture_echo","hero_fixture_warden"]);});
test("tampered file blocks",async()=>{const o=await built();await fs.appendFile(path.join(o,"unit.json")," ");await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("missing file blocks",async()=>{const o=await built();await fs.rm(path.join(o,"unit.json"));await assert.rejects(()=>loadVerifiedBundle(o));});
test("count mismatch blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.counts.unit=999;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_COUNT/);});
test("unsafe manifest path blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.files[0].path="../evil.json";await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("outer byType map immutable",async()=>{const b=await loadVerifiedBundle(await built());assert.throws(()=>b.byType.set("x",new Map()),/P09_IMMUTABLE_BUNDLE/);});
test("inner entity map immutable",async()=>{const b=await loadVerifiedBundle(await built());assert.throws(()=>b.byType.get("unit").set("x",{}),/P09_IMMUTABLE_BUNDLE/);});
test("malformed file record blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.files[0]={path:"x.json"};await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
