import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs/promises";import path from "node:path";import os from "node:os";import { compileGraph } from "../../tools/content/lib/compiler-core.mjs";import { loadSource,loadLocaleKeys } from "../../tools/content/lib/source-loader.mjs";import { loadVerifiedBundle } from "../../tools/content/lib/runtime-core.mjs";import { starterRoot } from "./test-helpers.mjs";
async function built(){const o=await fs.mkdtemp(path.join(os.tmpdir(),"p09-runtime-"));await compileGraph({root:starterRoot,outDir:o,profile:"fixture",loadSource,loadLocaleKeys});return o;}
test("verified runtime loads atomically",async()=>{const b=await loadVerifiedBundle(await built());assert.equal(b.byType.get("unit").size,2);});
test("entities deep frozen",async()=>{const b=await loadVerifiedBundle(await built());const e=b.byType.get("unit").get("hero_fixture_warden");assert.equal(Object.isFrozen(e),true);assert.equal(Object.isFrozen(e.baseStats),true);});
test("stable map insertion order",async()=>{const b=await loadVerifiedBundle(await built());assert.deepEqual([...b.byType.get("unit").keys()],["enemy_fixture_echo","hero_fixture_warden"]);});
test("tampered file blocks",async()=>{const o=await built();await fs.appendFile(path.join(o,"unit.json")," ");await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("missing file blocks",async()=>{const o=await built();await fs.rm(path.join(o,"unit.json"));await assert.rejects(()=>loadVerifiedBundle(o));});
test("count mismatch blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.counts.unit=999;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_COUNT/);});
test("unsafe manifest path blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.files[0].path="../evil.json";await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("outer byType map immutable",async()=>{const b=await loadVerifiedBundle(await built());assert.throws(()=>b.byType.set("x",new Map()),/P09_IMMUTABLE_BUNDLE/);});
test("inner entity map immutable",async()=>{const b=await loadVerifiedBundle(await built());assert.throws(()=>b.byType.get("unit").set("x",{}),/P09_IMMUTABLE_BUNDLE/);});
test("malformed file record blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.files[0]={path:"x.json"};await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("missing manifest blocks",async()=>{const o=await built();await fs.rm(path.join(o,"manifest.json"));await assert.rejects(()=>loadVerifiedBundle(o));});
test("wrong byteLength blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));const f=m.files.find((x)=>x.path==="unit.json");f.byteLength+=1;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_MANIFEST_HASH/);});
test("tampered contentVersion blocks",async()=>{const o=await built();const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));m.contentVersion="0".repeat(64);await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_CONTENT_VERSION/);});
test("unknown generated header blocks",async()=>{const o=await built();const u=JSON.parse(await fs.readFile(path.join(o,"unit.json")));u.generatedBy="evil";await fs.writeFile(path.join(o,"unit.json"),JSON.stringify(u));const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));const f=m.files.find((x)=>x.path==="unit.json");const crypto=await import("node:crypto");const bytes=Buffer.from(JSON.stringify(u));f.sha256=crypto.createHash("sha256").update(bytes).digest("hex");f.byteLength=bytes.length;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_SCHEMA_TYPE/);});
test("unknown generated schemaVersion blocks",async()=>{const o=await built();const u=JSON.parse(await fs.readFile(path.join(o,"unit.json")));u.schemaVersion=99;await fs.writeFile(path.join(o,"unit.json"),JSON.stringify(u));const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));const f=m.files.find((x)=>x.path==="unit.json");const crypto=await import("node:crypto");const bytes=Buffer.from(JSON.stringify(u));f.sha256=crypto.createHash("sha256").update(bytes).digest("hex");f.byteLength=bytes.length;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_SCHEMA_TYPE/);});
test("duplicate generated ID blocks",async()=>{const o=await built();const u=JSON.parse(await fs.readFile(path.join(o,"unit.json")));u.entities.push({...u.entities[0]});await fs.writeFile(path.join(o,"unit.json"),JSON.stringify(u));const m=JSON.parse(await fs.readFile(path.join(o,"manifest.json")));const f=m.files.find((x)=>x.path==="unit.json");const crypto=await import("node:crypto");const bytes=Buffer.from(JSON.stringify(u));f.sha256=crypto.createHash("sha256").update(bytes).digest("hex");f.byteLength=bytes.length;await fs.writeFile(path.join(o,"manifest.json"),JSON.stringify(m));await assert.rejects(()=>loadVerifiedBundle(o),/P09_ID_COLLISION/);});
test("index entity loads with pool/compat/codex maps",async()=>{const b=await loadVerifiedBundle(await built());const index=b.byType.get("index").get("content-index");assert.equal(index.pools.encounter["mission_fixture_1"][0],"encounter_fixture_first");assert.equal(index.compatibility.item["item_fixture_blade"][0],"hero_fixture_warden");assert.equal(index.codex.unit["hero_fixture_warden"],"screen_fixture_codex");});
