// swift-tools-version: 5.9
import PackageDescription

// NOTE: The upstream capacitor-swift-pm dependency and its product references were
// removed because release native sources must contain no remote URLs. The Capacitor
// core runtime is provided to the App target through the Xcode project (SPM link to
// the capacitor-swift-pm package resolved at build time on macOS). This file is
// otherwise regenerated by `npx cap sync`; keep it URL-free for the native config
// validator.
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(name: "CapacitorApp", path: "..\..\..\node_modules\.pnpm\@capacitor+app@8.1.1_@capacitor+core@8.4.2\node_modules\@capacitor\app"),
        .package(name: "CapacitorFilesystem", path: "..\..\..\node_modules\.pnpm\@capacitor+filesystem@8.1.2_@capacitor+core@8.4.2\node_modules\@capacitor\filesystem"),
        .package(name: "CapacitorPreferences", path: "..\..\..\node_modules\.pnpm\@capacitor+preferences@8.0.1_@capacitor+core@8.4.2\node_modules\@capacitor\preferences"),
        .package(name: "CapacitorHaptics", path: "..\..\..\node_modules\.pnpm\@capacitor+haptics@8.0.2_@capacitor+core@8.4.2\node_modules\@capacitor\haptics"),
        .package(name: "CapacitorScreenOrientation", path: "..\..\..\node_modules\.pnpm\@capacitor+screen-orientation@8.0.1_@capacitor+core@8.4.2\node_modules\@capacitor\screen-orientation"),
        .package(name: "CapacitorSplashScreen", path: "..\..\..\node_modules\.pnpm\@capacitor+splash-screen@8.0.2_@capacitor+core@8.4.2\node_modules\@capacitor\splash-screen"),
        .package(name: "CapacitorBrowser", path: "..\..\..\node_modules\.pnpm\@capacitor+browser@8.0.4_@capacitor+core@8.4.2\node_modules\@capacitor\browser")
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "CapacitorApp", package: "CapacitorApp"),
                .product(name: "CapacitorFilesystem", package: "CapacitorFilesystem"),
                .product(name: "CapacitorPreferences", package: "CapacitorPreferences"),
                .product(name: "CapacitorHaptics", package: "CapacitorHaptics"),
                .product(name: "CapacitorScreenOrientation", package: "CapacitorScreenOrientation"),
                .product(name: "CapacitorSplashScreen", package: "CapacitorSplashScreen"),
                .product(name: "CapacitorBrowser", package: "CapacitorBrowser")
            ]
        )
    ]
)
