export const EVENT_SPEC = Object.freeze({
  BattleStarted:{category:'lifecycle',payload:['battleOrdinal']}, PhaseStarted:{category:'lifecycle',payload:['phaseOrdinal']}, BattleEnded:{category:'lifecycle',payload:['outcomeOrdinal']},
  Spawned:{category:'entity',payload:['x100','laneOrdinal']}, Activated:{category:'entity',payload:[]}, TargetChanged:{category:'entity',payload:[]}, MovedLane:{category:'entity',payload:['fromLane','toLane']}, Defeated:{category:'entity',payload:['overkill']}, Removed:{category:'entity',payload:[]}, Revived:{category:'entity',payload:['restoredLp']},
  AttackPrepared:{category:'combat',payload:['commitTick']}, AttackInterrupted:{category:'combat',payload:['reasonOrdinal']}, AttackCommitted:{category:'combat',payload:['commitTick']}, AttackRecoveryStarted:{category:'combat',payload:['recoveryEndTick']}, AttackCycleCompleted:{category:'combat',payload:[]}, ProjectileSpawned:{category:'combat',payload:['impactTick']}, DamageApplied:{category:'combat',payload:['rawAmount','damageTypeOrdinal','effectiveDefense','preShieldAmount','absorbedShield','finalHpDelta','hpBefore','hpAfter','shieldBefore','shieldAfter','attackInstanceId','effectIndex']}, HealApplied:{category:'combat',payload:['rawAmount','finalHpDelta','hpBefore','hpAfter','attackInstanceId','effectIndex']}, ShieldApplied:{category:'combat',payload:['rawAmount','remaining','expiryTick','priority','shieldBefore','shieldAfter','attackInstanceId','effectIndex']}, ShieldAbsorbed:{category:'combat',payload:['amount','remaining']}, ShieldExpired:{category:'combat',payload:['amount']}, EffectApplied:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal']}, EffectRefreshed:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal']}, EffectIgnored:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal','ignoreReasonOrdinal']}, EffectRemoved:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal','reasonOrdinal']}, EffectTick:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal','tickIndex']}, EffectResisted:{category:'combat',payload:['stackCount','endTick','strength','kindOrdinal']},
  ChargeReady:{category:'ability',payload:['chargeTicks']}, AbilityPrepared:{category:'ability',payload:['commitTick']}, AbilityInterrupted:{category:'ability',payload:['remainingChargeTicks']}, AbilityCommitted:{category:'ability',payload:['commitTick']}, AbilityResolved:{category:'ability',payload:['effectCount']},
  AbilityTriggered:{category:'ability',payload:['triggerOrdinal']}, AbilityTargetSelected:{category:'ability',payload:[]}, AbilityWaitingTarget:{category:'ability',payload:[]}, AbilityCastStarted:{category:'ability',payload:['commitTick']}, AbilityEffectQueued:{category:'ability',payload:['effectIndex']}, AbilityRecovered:{category:'ability',payload:[]}, AbilityCooldownStarted:{category:'ability',payload:['cooldownTicks']}, AbilityReady:{category:'ability',payload:['chargeTicks']}, AbilityConsumed:{category:'ability',payload:['usesRemaining']}, AbilityRejected:{category:'ability',payload:['reasonOrdinal']},
  ModifierTriggered:{category:'world',payload:['triggerOrdinal']}, HazardTelegraphed:{category:'world',payload:['resolveTick']}, HazardResolved:{category:'world',payload:['effectCount']}, ReinforcementQueued:{category:'world',payload:['spawnTick']}, ReinforcementSpawned:{category:'world',payload:['count']},
  PhaseTransitionPlanned:{category:'boss',payload:['commitTick']}, BossTelegraphStarted:{category:'boss',payload:['resolveTick']}, BossPhaseStarted:{category:'boss',payload:[]}, BossPhaseCompleted:{category:'boss',payload:[]},
  InvalidTargetPrevented:{category:'diagnostics',payload:['policyOrdinal']}, SummonLimitBlocked:{category:'diagnostics',payload:['activeCount']}, FallbackRuleUsed:{category:'diagnostics',payload:['ruleOrdinal']}, SafetyCapTriggered:{category:'diagnostics',payload:['capOrdinal','observed']},
  LaneLogicalSwitched:{category:'entity',payload:['fromLane','toLane']}, LaneChangeCompleted:{category:'entity',payload:['fromLane','toLane']}, LaneChangeInterrupted:{category:'entity',payload:['reasonOrdinal']},
  StuckRepath:{category:'diagnostics',payload:['noProgressTicks']}, RepathLaneUnavailable:{category:'diagnostics',payload:['noProgressTicks']}, FrontDeadlockRangeBoost:{category:'diagnostics',payload:['blockedTicks']}, RiftCollapseWarning:{category:'diagnostics',payload:['noProgressTicks']}, RiftCollapseEndRequest:{category:'diagnostics',payload:['collapseTicks']}, SpawnRejected:{category:'diagnostics',payload:['reasonOrdinal']}
} as const);
export type EventType=keyof typeof EVENT_SPEC;
export type EventCategory=(typeof EVENT_SPEC)[EventType]['category'];
